import uuid
from datetime import datetime
from typing import Optional, List
from pydantic import EmailStr
from sqlmodel import SQLModel, Field, Relationship

# class Upload(SQLModel, table=True):
#     id: str = Field(primary_key=True)
#     filename: str
#     author: str
#     language: str
#     date_added: datetime = Field(default_factory=lambda: datetime.now()) # auto-generated by Python
#     size: int  # in bytes
#     file_type: str
#     source_filename: str
#     pages: int
#     status: int
#     s3_key: str

# Shared properties
class UploadBase(SQLModel):
    filename: str = Field(max_length=255)
    author: str = Field(max_length=255)
    language: str = Field(max_length=10)
    publication_date: Optional[datetime] = None

class Upload(UploadBase, table=True):
    __tablename__ = "upload"  # ensure exact name if needed
    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    date_added: datetime = Field(default_factory=datetime.now, nullable=False)
    size: int  # consider BigInteger in MySQL if files can be large
    file_type: str = Field(max_length=50)
    source_filename: str = Field(max_length=255)
    pages: int
    status: int
    s3_key: str = Field(max_length=512)

