[project]
name = "backend"
version = "0.1.0"
description = "Backend Dependencies Management"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.1",
    "sqlmodel>=0.0.24",
]
