"""add legacy_id to fix malformed id

Revision ID: 7527e1a49b22
Revises: ff3027c733ed
Create Date: 2025-12-31 15:18:42.271905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7527e1a49b22'
down_revision: Union[str, None] = 'ff3027c733ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1) add legacy_id
    op.add_column(
        "upload",
        sa.Column("legacy_id", mysql.CHAR(length=32), nullable=True),
    )

    # 2) copy old ids into legacy_id
    op.execute("UPDATE upload SET legacy_id = id")

    # 3) add new id (char32 for uuid.hex)
    op.add_column(
        "upload",
        sa.Column("new_id", mysql.CHAR(length=32), nullable=True),
    )

    # 4) fill new_id with fresh UUIDs (hyphenless)
    op.execute("UPDATE upload SET new_id = REPLACE(UUID(), '-', '') WHERE new_id IS NULL")

    # 5) drop existing PK on id
    op.drop_constraint("PRIMARY", "upload", type_="primary")

    # 6) drop the old id column now that its value is saved in legacy_id
    op.drop_column("upload", "id")

    # 7) rename new_id -> id (make it NOT NULL)
    op.alter_column(
        "upload", 
        "new_id", 
        new_column_name="id", 
        existing_type=mysql.CHAR(length=32),
        nullable=False,
    )

    # 8) set PK on new id column
    op.create_primary_key("pk_upload", "upload", ["id"])
    # legacy_id stays as is

    # 7) fix foreign keys if any (example; adjust names/tables/cols)
    # op.drop_constraint("fk_other_upload_id", "other_table", type_="foreignkey")
    # op.create_foreign_key("fk_other_upload_id", "other_table", "upload", ["upload_id"], ["id"])
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'legacy_id')
    # ### end Alembic commands ###
