"""refine upload schema

Revision ID: c704289ba0cf
Revises: 0aaeed04f110
Create Date: 2025-10-14 19:00:52.721288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c704289ba0cf'
down_revision: Union[str, None] = '0aaeed04f110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 'language',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.alter_column('upload', 'id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('upload', 'file_type',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=50),
               existing_nullable=False)
    op.alter_column('upload', 's3_key',
               existing_type=mysql.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=512),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload', 's3_key',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('upload', 'file_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('upload', 'id',
               existing_type=sa.Uuid(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('upload', 'language',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
