"""add publication_date to upload

Revision ID: ff3027c733ed
Revises: c704289ba0cf
Create Date: 2025-12-12 16:20:20.686357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ff3027c733ed'
down_revision: Union[str, None] = 'c704289ba0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload', sa.Column('publication_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload', 'publication_date')
    # ### end Alembic commands ###
