
from time import time
import asyncio

from app.core.db_redis import get_chat_messages, add_chat_messages

def chat_stream(messages, **kwargs):
    '''
    streaming response from AI model
    '''
    pass

MAIN_SYSTEM_PROMPT = ""
class Assistant:
    def __init__(self, rdb, chat_id, history_size=4):
        self.rdb = rdb # Redis connection
        self.chat_id = chat_id
        self.history_size = history_size # number of last messages fetched from redist for current chat_id
        self.sse_stream = None
        self.main_system_message = {'role': 'system', 'content': MAIN_SYSTEM_PROMPT}
        
    
    async def _generate_chat_response(self, system_message, chat_messages, **kwargs):
        '''
        This method checks every chunk in the response stream generated by the LLM. If it's of type 'content.delta' (containing new text content), we stream it to the client in real-time using the sse_stream object. At the end, we call the get_final_completion method to get the final accumulated response once it has been fully generated, including the full content and any tool calls if the model decides it needs them.

        TODO:
        how is content.delta type defined?
        '''
        messages = [system_message, *chat_messages]
        async with chat_stream(messages=messages, **kwargs) as stream:
            async for event in stream:
                if event.type == 'content.delta':
                    await self.sse_stream.send(event.delta)

            final_completion = await stream.get_final_completion()
            assistant_message = final_completion.choices[0].message
            return assistant_message
    
    async def _handle_tool_calls(self, tool_calls, chat_messages):
        pass

    async def _run_conversation_step(self, message):
        user_db_message = {'role': 'user', 'content': message, 'created_at': int(time())}
        # get last n messages from redis for current chat_id
        chat_messages = await get_chat_messages(self.rdb, self.chat_id, last_n=self.history_size)
        chat_messages.append({'role': 'user', 'content': message})
        assistant_message = await self._generate_chat_response(
            system_message=self.main_system_message, 
            chat_messages=chat_messages,
        )

        assistant_db_message = {
            'role': 'assistant',
            'content': assistant_message.content,
            'created_at': int(time()),
        }
        # append new user message and assistant message to redis
        await add_chat_messages(self.rdb, self.chat_id, [user_db_message, assistant_db_message])

    
    async def _handle_conversation_task(self, message):
        try:
            await self._run_conversation_step(message)
        except Exception as e:
            # TODO: improve error handling (send SSE message to client)
            print(f"Error: {str(e)}")
        finally:
            await self.sse_stream.close()
    
    def run(self, message):
        self.sse_stream = SSEStream()
        asyncio.create_task(self._handle_conversation_task(message))
        return self.sse_stream

    